select * from customer

--total revenue generated by male V/S female

select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;




--which customer used a discount but still spent more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);




-- which are the top 5 products with the highest average review rating

select item_purchased, avg(review_rating)::numeric(10,2) as rating
from customer
group by item_purchased
order by rating desc
limit 5;



-- compare the average purchase amounts between standard and express shipping

select shipping_type, avg(purchase_amount)::numeric(10,2) as amount
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;



-- Do subscriber customer spend more? Campare average spend and total revenue 
-- between subscriber and non- subscriber

select subscription_status, 
count(customer_id) as total_customer,
avg(purchase_amount)::numeric(10,2) as avg_spend,
sum(purchase_amount)::numeric(10,2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;




-- whish 5 product have the highest percentage of purchase with discount applied

select item_purchased,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*) , 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;



-- segment customer into new, returin and loyal based on their total number of pervious
-- purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'return'
	else 'loyal' 
	end as customer_segment
from customer
)

select customer_segment, count(*) as no_of_customer
from customer_type
group by customer_segment
order by no_of_customer;



-- what are the top 3 most purchased product within each category
with item_counts as(
select item_purchased, category, count(customer_id) as total_count,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_count
from item_counts
where item_rank <= 3;


-- are customer who are repeat buyer (more then 5  previous purchase) also likely to subsccribe

select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status;

-- check the revenue by age group

select Aged_group, sum(purchase_amount) as total_revenue
from customer
group by Aged_group
order by total_revenue desc;



